name: bokain_admin
description: Administration dashboard for bokain booking system
version: 0.1.0
environment:
  sdk: '>=1.24.2 <2.0.0'
dependencies:
  angular: "^4.0.0"
  angular_components: "^0.6.0"
  bokain_calendar:
    path: ../bokain-calendar/
  bokain_models:
    path: ../bokain-models/
  angular_modern_charts: ^0.0.9
  d_components: any
  fo_components:
    path: ../../Visurus/FoComponents/
  firebase: ^4.0.0

dev_dependencies:
  browser: ^0.10.0+2
  dart_to_js_script_rewriter: ^1.0.3

transformers:
- angular:
    entry_points: web/main.dart
- dart_to_js_script_rewriter
