name: bokain_admin
description: Administration dashboard for bokain booking system
version: 0.1.1
environment:
  sdk: '>=1.24.2 <2.0.0'

dependencies:
  angular: "^4.0.0"
  angular_components: "^0.8.0"
  bokain_calendar:
    path: ../bokain-calendar/
  bokain_models:
    path: ../bokain-models/
  angular_modern_charts:
    path: ../../dejan/angular_modern_charts/
  d_components:
    path: ../../dejan/d_components/
  fo_components:
    path: ../../Visurus/FoComponents/
  firebase: ^4.1.0
  grid:
    path: ../../Visurus/Grid/
  dart_to_js_script_rewriter: ^1.0.3

dev_dependencies:
  browser: ^0.10.0+2
  angular_test: ^1.0.0
  test: ^0.12.21
  sass_builder: ^1.0.1

transformers:
- sass_builder:
    outputExtension: .scss.css
- angular:
    entry_points:
    - web/main.dart
    - test/**_test.dart
- test/pub_serve:
    $include: test/**_test.dart
- dart_to_js_script_rewriter

web:
  compiler:
    debug: dartdevc